/*==========================================================================  
 |   Source code:  PrimeSequence.java
 |        Author:  Dylan Sumler
 |    Student ID:  3538998  
 |    Assignment:  Assignment #4 - Better Rectangle
 |  
 |        Course:  COP 3337 (Programming II) 
 |       Section:  U02  
 |    Instructor:  William Feild  
 |      Due Date:  7 March 2017, class time
 |
 |	I hereby certify that this collective work is my own
 |	and none of it is the work of any other person or entity.
 |	______________________________________ [Signature]
 |  
 |      Language:  Java 
 |   Compile/Run:  javac BetterRectangle.java BRectTester.java
 |                 java BRectTester
 | 
 |  +-----------------------------------------------------------------------  
 |  
 |  Description:  This class creates expands on the functionality of the
 |                standard Rectangle class in java by adding methods to 
 |                retrive additionaly rectangle information including 
 |                perimeter, slope, midpoint, and area. It also allows for
 |                rectangles to be compared based of this additional 
 |                parameters.
 |
 |        Input:  No input will be used for this class.
 |  
 |       Output:  No output will be generated by this class.
 |  
 |      Process:  A BetterRectangle can be created from one of four 
 |                constructors. The toString method from the Rectangle
 |                superclass was overridden to take into account the 
 |                additional rectangle parameters that can be calculated.
 |
 |                
 |  
 |   Required Features Not Included: All required features are included.
 |                 
 |  
 |   Known Bugs: None; the program operates as intended. 
 |  *======================================================================*/

package assignment5;

/**
 *
 * @author Dylan
 */
public class PrimeSequence {

   /**
    * @param args the command line arguments
    */
   public static void main(String[] args) {
      // TODO code application logic here
   }
   
}
